/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuthRouteImport } from './routes/admin/_auth'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ProyektorProyektorRouteImport } from './routes/proyektor/_proyektor'
import { Route as AdminAuthSkorRouteImport } from './routes/admin/_auth/skor'
import { Route as AdminAuthSoalBabakRouteImport } from './routes/admin/_auth/soal-babak'
import { Route as AdminAuthUsersRouteImport } from './routes/admin/_auth/users'
import { Route as AdminAuthWaktuRouteImport } from './routes/admin/_auth/waktu'
import { Route as ProyektorProyektorIndexRouteImport } from './routes/proyektor/_proyektor/index'
import { Route as ProyektorProyektorSkorRouteImport } from './routes/proyektor/_proyektor/skor'
import { Route as ProyektorProyektorBabak1RouteImport } from './routes/proyektor/_proyektor/babak/1'
import { Route as ProyektorProyektorBabak2RouteImport } from './routes/proyektor/_proyektor/babak/2'
import { Route as ProyektorProyektorBabak3RouteImport } from './routes/proyektor/_proyektor/babak/3'
import { Route as ProyektorProyektorBabak4RouteImport } from './routes/proyektor/_proyektor/babak/4'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyektorProyektorRoute = ProyektorProyektorRouteImport.update({
  id: '/proyektor/_proyektor',
  path: '/proyektor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthSkorRoute = AdminAuthSkorRouteImport.update({
  id: '/skor',
  path: '/skor',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthSoalBabakRoute = AdminAuthSoalBabakRouteImport.update({
  id: '/soal-babak',
  path: '/soal-babak',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthUsersRoute = AdminAuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthWaktuRoute = AdminAuthWaktuRouteImport.update({
  id: '/waktu',
  path: '/waktu',
  getParentRoute: () => AdminAuthRoute,
} as any)
const ProyektorProyektorIndexRoute = ProyektorProyektorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProyektorProyektorRoute,
} as any)
const ProyektorProyektorSkorRoute = ProyektorProyektorSkorRouteImport.update({
  id: '/skor',
  path: '/skor',
  getParentRoute: () => ProyektorProyektorRoute,
} as any)
const ProyektorProyektorBabak1Route =
  ProyektorProyektorBabak1RouteImport.update({
    id: '/babak/1',
    path: '/babak/1',
    getParentRoute: () => ProyektorProyektorRoute,
  } as any)
const ProyektorProyektorBabak2Route =
  ProyektorProyektorBabak2RouteImport.update({
    id: '/babak/2',
    path: '/babak/2',
    getParentRoute: () => ProyektorProyektorRoute,
  } as any)
const ProyektorProyektorBabak3Route =
  ProyektorProyektorBabak3RouteImport.update({
    id: '/babak/3',
    path: '/babak/3',
    getParentRoute: () => ProyektorProyektorRoute,
  } as any)
const ProyektorProyektorBabak4Route =
  ProyektorProyektorBabak4RouteImport.update({
    id: '/babak/4',
    path: '/babak/4',
    getParentRoute: () => ProyektorProyektorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/proyektor': typeof ProyektorProyektorRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/skor': typeof AdminAuthSkorRoute
  '/admin/soal-babak': typeof AdminAuthSoalBabakRoute
  '/admin/users': typeof AdminAuthUsersRoute
  '/admin/waktu': typeof AdminAuthWaktuRoute
  '/proyektor/skor': typeof ProyektorProyektorSkorRoute
  '/proyektor/': typeof ProyektorProyektorIndexRoute
  '/proyektor/babak/1': typeof ProyektorProyektorBabak1Route
  '/proyektor/babak/2': typeof ProyektorProyektorBabak2Route
  '/proyektor/babak/3': typeof ProyektorProyektorBabak3Route
  '/proyektor/babak/4': typeof ProyektorProyektorBabak4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/skor': typeof AdminAuthSkorRoute
  '/admin/soal-babak': typeof AdminAuthSoalBabakRoute
  '/admin/users': typeof AdminAuthUsersRoute
  '/admin/waktu': typeof AdminAuthWaktuRoute
  '/proyektor/skor': typeof ProyektorProyektorSkorRoute
  '/proyektor': typeof ProyektorProyektorIndexRoute
  '/proyektor/babak/1': typeof ProyektorProyektorBabak1Route
  '/proyektor/babak/2': typeof ProyektorProyektorBabak2Route
  '/proyektor/babak/3': typeof ProyektorProyektorBabak3Route
  '/proyektor/babak/4': typeof ProyektorProyektorBabak4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/proyektor/_proyektor': typeof ProyektorProyektorRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/_auth/skor': typeof AdminAuthSkorRoute
  '/admin/_auth/soal-babak': typeof AdminAuthSoalBabakRoute
  '/admin/_auth/users': typeof AdminAuthUsersRoute
  '/admin/_auth/waktu': typeof AdminAuthWaktuRoute
  '/proyektor/_proyektor/skor': typeof ProyektorProyektorSkorRoute
  '/proyektor/_proyektor/': typeof ProyektorProyektorIndexRoute
  '/proyektor/_proyektor/babak/1': typeof ProyektorProyektorBabak1Route
  '/proyektor/_proyektor/babak/2': typeof ProyektorProyektorBabak2Route
  '/proyektor/_proyektor/babak/3': typeof ProyektorProyektorBabak3Route
  '/proyektor/_proyektor/babak/4': typeof ProyektorProyektorBabak4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/proyektor'
    | '/admin/'
    | '/admin/skor'
    | '/admin/soal-babak'
    | '/admin/users'
    | '/admin/waktu'
    | '/proyektor/skor'
    | '/proyektor/'
    | '/proyektor/babak/1'
    | '/proyektor/babak/2'
    | '/proyektor/babak/3'
    | '/proyektor/babak/4'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/admin/skor'
    | '/admin/soal-babak'
    | '/admin/users'
    | '/admin/waktu'
    | '/proyektor/skor'
    | '/proyektor'
    | '/proyektor/babak/1'
    | '/proyektor/babak/2'
    | '/proyektor/babak/3'
    | '/proyektor/babak/4'
  id:
    | '__root__'
    | '/'
    | '/admin/_auth'
    | '/admin/login'
    | '/proyektor/_proyektor'
    | '/admin/'
    | '/admin/_auth/skor'
    | '/admin/_auth/soal-babak'
    | '/admin/_auth/users'
    | '/admin/_auth/waktu'
    | '/proyektor/_proyektor/skor'
    | '/proyektor/_proyektor/'
    | '/proyektor/_proyektor/babak/1'
    | '/proyektor/_proyektor/babak/2'
    | '/proyektor/_proyektor/babak/3'
    | '/proyektor/_proyektor/babak/4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ProyektorProyektorRoute: typeof ProyektorProyektorRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyektor/_proyektor': {
      id: '/proyektor/_proyektor'
      path: '/proyektor'
      fullPath: '/proyektor'
      preLoaderRoute: typeof ProyektorProyektorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/skor': {
      id: '/admin/_auth/skor'
      path: '/skor'
      fullPath: '/admin/skor'
      preLoaderRoute: typeof AdminAuthSkorRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/soal-babak': {
      id: '/admin/_auth/soal-babak'
      path: '/soal-babak'
      fullPath: '/admin/soal-babak'
      preLoaderRoute: typeof AdminAuthSoalBabakRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/users': {
      id: '/admin/_auth/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthUsersRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/waktu': {
      id: '/admin/_auth/waktu'
      path: '/waktu'
      fullPath: '/admin/waktu'
      preLoaderRoute: typeof AdminAuthWaktuRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/proyektor/_proyektor/': {
      id: '/proyektor/_proyektor/'
      path: '/'
      fullPath: '/proyektor/'
      preLoaderRoute: typeof ProyektorProyektorIndexRouteImport
      parentRoute: typeof ProyektorProyektorRoute
    }
    '/proyektor/_proyektor/skor': {
      id: '/proyektor/_proyektor/skor'
      path: '/skor'
      fullPath: '/proyektor/skor'
      preLoaderRoute: typeof ProyektorProyektorSkorRouteImport
      parentRoute: typeof ProyektorProyektorRoute
    }
    '/proyektor/_proyektor/babak/1': {
      id: '/proyektor/_proyektor/babak/1'
      path: '/babak/1'
      fullPath: '/proyektor/babak/1'
      preLoaderRoute: typeof ProyektorProyektorBabak1RouteImport
      parentRoute: typeof ProyektorProyektorRoute
    }
    '/proyektor/_proyektor/babak/2': {
      id: '/proyektor/_proyektor/babak/2'
      path: '/babak/2'
      fullPath: '/proyektor/babak/2'
      preLoaderRoute: typeof ProyektorProyektorBabak2RouteImport
      parentRoute: typeof ProyektorProyektorRoute
    }
    '/proyektor/_proyektor/babak/3': {
      id: '/proyektor/_proyektor/babak/3'
      path: '/babak/3'
      fullPath: '/proyektor/babak/3'
      preLoaderRoute: typeof ProyektorProyektorBabak3RouteImport
      parentRoute: typeof ProyektorProyektorRoute
    }
    '/proyektor/_proyektor/babak/4': {
      id: '/proyektor/_proyektor/babak/4'
      path: '/babak/4'
      fullPath: '/proyektor/babak/4'
      preLoaderRoute: typeof ProyektorProyektorBabak4RouteImport
      parentRoute: typeof ProyektorProyektorRoute
    }
  }
}

interface AdminAuthRouteChildren {
  AdminAuthSkorRoute: typeof AdminAuthSkorRoute
  AdminAuthSoalBabakRoute: typeof AdminAuthSoalBabakRoute
  AdminAuthUsersRoute: typeof AdminAuthUsersRoute
  AdminAuthWaktuRoute: typeof AdminAuthWaktuRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthSkorRoute: AdminAuthSkorRoute,
  AdminAuthSoalBabakRoute: AdminAuthSoalBabakRoute,
  AdminAuthUsersRoute: AdminAuthUsersRoute,
  AdminAuthWaktuRoute: AdminAuthWaktuRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

interface ProyektorProyektorRouteChildren {
  ProyektorProyektorSkorRoute: typeof ProyektorProyektorSkorRoute
  ProyektorProyektorIndexRoute: typeof ProyektorProyektorIndexRoute
  ProyektorProyektorBabak1Route: typeof ProyektorProyektorBabak1Route
  ProyektorProyektorBabak2Route: typeof ProyektorProyektorBabak2Route
  ProyektorProyektorBabak3Route: typeof ProyektorProyektorBabak3Route
  ProyektorProyektorBabak4Route: typeof ProyektorProyektorBabak4Route
}

const ProyektorProyektorRouteChildren: ProyektorProyektorRouteChildren = {
  ProyektorProyektorSkorRoute: ProyektorProyektorSkorRoute,
  ProyektorProyektorIndexRoute: ProyektorProyektorIndexRoute,
  ProyektorProyektorBabak1Route: ProyektorProyektorBabak1Route,
  ProyektorProyektorBabak2Route: ProyektorProyektorBabak2Route,
  ProyektorProyektorBabak3Route: ProyektorProyektorBabak3Route,
  ProyektorProyektorBabak4Route: ProyektorProyektorBabak4Route,
}

const ProyektorProyektorRouteWithChildren =
  ProyektorProyektorRoute._addFileChildren(ProyektorProyektorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ProyektorProyektorRoute: ProyektorProyektorRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
